Feature/dynamic column #7
digitalnomadacademy/youthetree pull request #14
Opened 2020-04-16 10:01 UTC by Noamagnus

#7 

https://gyazo.com/c846218bc6d33749b44a614a45bb0bbf

2020-04-16 12:19 UTC, Egle0111 approved these changes

2020-04-16 17:29 UTC, MrgaCRO approved these changes
Kod mene radi sve kako si i prikazao.

2020-04-20 17:08 UTC, matejthetree requested changes

2020-04-20 17:08 UTC, matejthetree commented on lib/ui/molecule/resize_widget.dart
> +    return Scaffold(
scaffold and appbar are not needed in organism widget

2020-04-20 17:08 UTC, matejthetree commented on lib/ui/molecule/resize_widget.dart
> +          Divider(
gesture detector needs to wrap divider, and not bottom container

2020-04-20 17:08 UTC, matejthetree commented on lib/ui/molecule/resize_widget.dart
> +          Divider(
you can make thickness/height a 3

2020-04-20 17:08 UTC, matejthetree commented on lib/ui/molecule/resize_widget.dart
> +          Divider(
thikness

2020-04-20 17:08 UTC, matejthetree commented on lib/ui/molecule/resize_widget.dart
> +          Divider(
or, wrap gesture detector around complete column, and then check if the (dx,dy) coordinates are close to the divider.

2020-04-20 17:08 UTC, matejthetree commented on lib/ui/molecule/resize_widget.dart
> +double containerHeight = 40;
this needs to be inside state

2020-04-20 17:08 UTC, matejthetree commented on lib/ui/molecule/resize_widget.dart
> +  @override
add container height here

2020-04-20 17:08 UTC, matejthetree commented on lib/ui/molecule/resize_widget.dart
> +class ResizeWidget extends StatefulWidget {
```
final Widget topChild;
final Widget bottomChild;
final double dividerPercentage;

... constructor
```

2020-04-20 17:08 UTC, matejthetree commented on lib/ui/molecule/resize_widget.dart
> +            child: Container(
widget.topChild

2020-04-20 17:08 UTC, matejthetree commented on lib/ui/molecule/resize_widget.dart
> +            child: Container(
`widget.bottomChild`

2020-04-20 17:08 UTC, matejthetree commented on lib/ui/molecule/resize_widget.dart
> +  @override
```
double _currentPercentage;
initState .... ->
 _currentPercentage = widget.dividerPercentage;
```

then inside build function, you will use this percentage to calculate container height from MediaQuery size

2020-04-20 17:08 UTC, matejthetree commented on lib/ui/molecule/resize_widget.dart
> +  @override
```
Column...
[
Expanded(flex: _currentPercantage*100),
Divider(),
Expanded(flex: (1-_currentPercantage)*100)
```

2020-04-23 23:48 UTC, matejthetree approved these changes
super. pobrisi komentare i mozemo mergat

2020-04-23 23:48 UTC, matejthetree commented on lib/ui/molecule/resize_widget.dart
> +//            print('global ${details.globalPosition.dy}');
pobrisi komentare

2020-04-23 23:48 UTC, matejthetree commented on lib/ui/molecule/resize_widget.dart
> +            print('current% $_currentPercentage'); //
ovo isto pobrisi ako si resio, neznam imamo li logger implementiran. za sada brisi.

2020-04-27 08:45 UTC, merged