onboarding page_first upload
digitalnomadacademy/youthetree pull request #17
Opened 2020-04-20 17:32 UTC by Tinjomar

#3 

https://gyazo.com/4b56dd4dd236a6df70c65a3ecf77cc45

2020-04-27 16:33 UTC, matejthetree requested changes

2020-04-27 16:33 UTC, matejthetree commented on code_onboarding_page.dart
> +  List<Slide> slides = new List();
`= [];`

2020-04-27 16:33 UTC, matejthetree commented on code_onboarding_page.dart
> +  List<Slide> slides = new List();
we dont use new

2020-04-27 16:33 UTC, matejthetree commented on code_onboarding_page.dart
> +      new Slide(
no `new`

2020-04-27 16:33 UTC, matejthetree commented on code_onboarding_page.dart
> +    // TODO: go to next screen
navigate to home page

2020-04-27 16:33 UTC, matejthetree commented on code_onboarding_page.dart
> +        nameNextBtn: ('SKIP'),
next

2020-04-27 16:33 UTC, matejthetree commented on lib/main.dart
> -    return MultiProvider(
nije dobro, ne brisati

2020-04-27 16:33 UTC, matejthetree commented on lib/main.dart
> +      home: OnBoardingPage (),
nije dobro, moras koristiti test rute, @Noamagnus moze objasnit

2020-04-27 16:33 UTC, matejthetree commented on lib/main.dart
> +      home: OnBoardingPage (),
ne treba test ruta, trebas napravit onboarding routu, jer ce ona biti u aplikaciji

2020-04-27 16:33 UTC, matejthetree commented on code_onboarding_page.dart
> +
samo `onboarding_page.dart`

2020-04-27 16:33 UTC, matejthetree commented on lib/ui/page/code_onboarding_page.dart
> +
zasto imamo dva onboarding pagea?

2020-04-29 18:38 UTC, Tinjomar commented on lib/ui/page/code_onboarding_page.dart
> +
slučajno

2020-04-29 23:53 UTC, Tinjomar reviewed
resolved

2020-05-04 17:25 UTC, matejthetree approved these changes
little changes and FORMATTING

2020-05-04 17:25 UTC, matejthetree commented on lib/ui/page/onboarding_page.dart
> +    Navigator.pushNamed(context, 'login');
`// todo add login route once finished`

Line 52 in .../..../.../ file add push to login route

2020-05-07 18:07 UTC, Noamagnus commented
Review done

2020-05-07 18:10 UTC, MrgaCRO approved these changes

2020-05-07 18:23 UTC, Noamagnus approved these changes
Approved

2020-05-11 18:39 UTC, matejthetree approved these changes

2020-05-11 18:40 UTC, matejthetree commented
rebase i merge

2020-05-11 20:17 UTC, merged