Feature/google map #10
digitalnomadacademy/youthetree pull request #18
Opened 2020-04-24 16:33 UTC by Egle0111

#10 

https://gyazo.com/3935b288ebed88d507c5df1f848c3094

2020-04-27 16:42 UTC, matejthetree requested changes

2020-04-27 16:42 UTC, matejthetree commented on lib/main.dart
> -class YTT extends StatelessWidget {
ovo treba napraviti kao sto radimo sve druge, napraviti test rutu za map. neka @Noamagnus  pomogne

2020-04-27 16:42 UTC, matejthetree commented on lib/ui/molecule/map_widget.dart
> +const LatLng SOURCE_LOCATION =
konstante se pisu normalnim camelCaseom `sourceLocation`
moze se dodati k prije konstante `kSourceLocation`

2020-04-27 16:42 UTC, matejthetree commented on lib/ui/molecule/map_widget.dart
> +    return MaterialApp(
za map widget nam ne treba material app. posto je samo widget, build funkcija vraca `GoogleMap`

2020-04-27 16:42 UTC, matejthetree commented on lib/ui/molecule/map_widget.dart
> +        body: GoogleMap(
ovo vraca build funkcija

2020-04-27 16:42 UTC, matejthetree commented on lib/ui/molecule/map_widget1.dart
> +import 'package:flutter/material.dart';
ovaj file nam je viska. Imamo samo jedan widget koji cemo koristiti. 

moze se zvati `MapWidget`

2020-04-27 16:42 UTC, matejthetree commented on pubspec.yaml
> +  fluttertoast: ^3.1.3
gdje koristis flutter toast?

2020-04-27 16:42 UTC, matejthetree commented on pubspec.yaml
> +  pedantic: ^1.4.0
gdje koristis ova dva plugina?

2020-04-27 16:42 UTC, matejthetree commented
pokrenuti u konzolu `flutter analyze` prije nego pushas

2020-04-29 16:08 UTC, Egle0111 commented on lib/ui/molecule/map_widget.dart
> +const LatLng SOURCE_LOCATION =
solved

2020-04-29 16:11 UTC, Egle0111 commented on lib/ui/molecule/map_widget.dart
> +    return MaterialApp(
bez material app kod buildanja javlja gresku da fali media query ili material app

2020-04-29 16:14 UTC, Egle0111 commented on lib/ui/molecule/map_widget1.dart
> +import 'package:flutter/material.dart';
solved - greskom commitano prije brisanja filea map_widget1

2020-04-29 16:17 UTC, Egle0111 commented on pubspec.yaml
> +  fluttertoast: ^3.1.3
nigdje - greskom ostalo iz prethodne verzije

2020-04-29 16:18 UTC, Egle0111 commented on pubspec.yaml
> +  pedantic: ^1.4.0
nigdje - greskom ostalo iz prethodne verzije

2020-04-29 16:21 UTC, Egle0111 commented on lib/ui/molecule/map_widget.dart
> +        body: GoogleMap(
bez MaterialApp pri buildanju vraca error da fali MediaQuery ili MaterialApp

2020-05-04 17:18 UTC, matejthetree requested changes

2020-05-04 17:18 UTC, matejthetree commented on lib/ui/molecule/map_widget.dart
> +const LatLng kSource_Location =
kSourceLocation

2020-05-04 17:18 UTC, matejthetree commented on lib/ui/molecule/map_widget.dart
> +class YttMapWidget extends StatefulWidget {
MapWidget

2020-05-04 17:18 UTC, matejthetree commented on lib/ui/molecule/map_widget.dart
> +    CameraPosition initialCameraPosition = CameraPosition(
move to state, as a field. initialize in initState

2020-05-04 17:18 UTC, matejthetree commented on lib/ui/molecule/map_widget.dart
> +    if (currentLocation != null) {
```
var cameraPosition;
cameraPosition = currrentLocation!=null 
? CameraPosition(
        target: LatLng(currentLocation.latitude, currentLocation.longitude),
        zoom: kCameraZoom,
      )
: initialCameraPositon;
```

2020-05-04 17:18 UTC, matejthetree commented on lib/ui/molecule/map_widget.dart
> +        body: GoogleMap(
Map Widget must have only GoogleMap as a child.

2020-05-04 17:18 UTC, matejthetree commented on lib/ui/molecule/map_widget.dart
> +        body: GoogleMap(
later create test page that will wrap maps in neccesary parent

```
class MapTest extends StatelessWidget {
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: YttMapWidget(),
    );
  }
}
```

2020-05-14 07:57 UTC, lea88pu approved these changes

2020-05-15 16:06 UTC, closed without merging