Origin/feature/share popup #8
digitalnomadacademy/youthetree pull request #19
Opened 2020-04-27 15:36 UTC by anikamile

#8
https://gyazo.com/1566ddc4adb1d04a5d3cb8c13b897f08
https://gyazo.com/d643ac4fc64a4cb01b5db322e6b4f570

2020-04-27 16:28 UTC, matejthetree requested changes

2020-04-27 16:28 UTC, matejthetree commented on lib/ui/organism/share_popup.dart
> +class SharePopupButton extends StatefulWidget {
stateless

2020-04-27 16:28 UTC, matejthetree commented on lib/ui/organism/share_popup.dart
> +            GestureDetector(
umjesto gesture detector `IconButton`

i vratis icon button u build funkciji

2020-04-27 16:28 UTC, matejthetree commented on lib/ui/organism/share_popup.dart
> +              onTap: () => Share.share(shareLink),
direktno staviti url

2020-05-04 13:52 UTC, anikamile reviewed
Made all the requested changes on share popup issue #8 file

2020-05-04 17:00 UTC, matejthetree requested changes
add test page, and test route

2020-05-04 17:00 UTC, matejthetree commented on lib/ui/organism/share_popup.dart
> +    return Card(
remove card

2020-05-04 17:00 UTC, matejthetree commented on lib/ui/organism/share_popup.dart
> +        padding: const EdgeInsets.all(50.0),
remove padding

2020-05-13 11:27 UTC, anikamile reviewed
#8
https://gyazo.com/85ddf36a436a9452862945c30dca4c4b
https://gyazo.com/2c8ddeb4eec179bef648b043e4399be9

2020-05-13 11:27 UTC, anikamile commented on lib/ui/organism/share_popup.dart
> +    return Card(
I did.

2020-05-13 11:27 UTC, anikamile commented on lib/ui/organism/share_popup.dart
> +        padding: const EdgeInsets.all(50.0),
I removed padding.

2020-05-15 16:06 UTC, closed without merging